# Generated by Django 2.2.6 on 2020-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200422_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('active', 'active'), ('busy', 'busy'), ('away', 'away')], default='away', max_length=20),
        ),
    ]
