# Generated by Django 2.2.6 on 2020-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200427_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('sales_person', 'Sales Person'), ('admin', 'Admin member')], max_length=255),
        ),
    ]
