# Generated by Django 2.2.6 on 2020-05-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200507_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(max_length=255)),
                ('parent_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='accounts.Location')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc_users', to='accounts.Location'),
        ),
    ]
