# Generated by Django 2.2.6 on 2020-05-13 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200513_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_loc',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_users', to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_users', to='accounts.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('country', 'country'), ('state', 'state'), ('city', 'city')], max_length=255),
        ),
    ]
